style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/HAECHI-LABS/core
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - ci
        - docs
  commit_groups:
    # title_order defines which group would be show first on CHANGELOG
    sort_by: "Custom"
    title_order:
      - feat
      - fix
      - perf
      - refactor
      - ci
      - docs
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      ci: CI
      docs: Document Updates
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE