apiRules:
  - include:
      uidRegex: ^haechi\.face\.unity\.sdk\.Runtime\.Module$
      type: Namespace
  - exclude:
      uidRegex: ^haechi\.face\.unity\.sdk\.Runtime\.Module\.IAuth$
      type: Interface
  - exclude:
      uidRegex: ^haechi\.face\.unity\.sdk\.Runtime\.Module\.IWallet$
      type: Interface
  - exclude:
      uidRegex: ^haechi\.face\.unity\.sdk\.Runtime\.Module\.AuthProxy$
      type: Class
  - exclude:
      uidRegex: ^haechi\.face\.unity\.sdk\.Runtime\.Module\.WalletProxy$
      type: Class
  - include:
      uidRegex: ^haechi\.face\.unity\.sdk\.Runtime\.Client\.Face$
      type: Namespace
  - include:
      uidRegex: ^haechi\.face\.unity\.sdk\.Runtime\.Client$
      type: Namespace
  - include:
      uidRegex: ^haechi\.face\.unity\.sdk\.Runtime\.Contract$
      type: Namespace
  - include:
      uidRegex: ^haechi\.face\.unity\.sdk\.Runtime$
      type: Namespace
  - exclude:
      uidRegex: ^.* # Every other namespaces are ignored
      type: Namespace