name: api-reference-docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Assets/haechi.face.unity.sdk'
      - 'Documentation'

jobs:
  api-reference-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Documentation
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: Documentation/docfx.json
      - name: 
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.DEV_NETLIFY_PAT }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          install_command: 'echo'
          build_command: 'echo'
          build_directory: '_site'
          