name: Tagging
run-name: Tagging ${{ github.event.inputs.semver }}
on:
  workflow_dispatch:
    inputs:
      semver:
        description: "Semantic version of release"
        required: true
jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - name: Install
        run: |
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
      - name: Zip android files
        run: |
          cd android-dependency-generator/Assets/Plugins/Android
          zip -r android-libraries.zip *.jar *.aar
          cd ../../../../
          
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.HAECHI_GITHUB_PAT }}
        with:
          tag_name: ${{ github.event.inputs.semver }}
          release_name: ${{ github.event.inputs.semver }}
          draft: false
          prerelease: false
          body_path: ./RELEASE_NOTE.md
          files: |
            android-dependency-generator/Assets/Plugins/Android/android-libraries.zip