name: Tagging
run-name: Tagging ${{ github.event.inputs.semver }}
on:
  workflow_dispatch:
    inputs:
      semver:
        description: "Semantic version of release"
        required: true
jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update package.json
        env:
          RELEASE_TAG: ${{ github.event.inputs.semver }}
        run: |
          tmp=$(mktemp)
          jq '.version = "'${RELEASE_TAG}'"' Assets/haechi.face.unity.sdk/package.json > $tmp && mv $tmp Assets/haechi.face.unity.sdk/package.json
      - name: Set up Golang
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.17
      - name: Install
        run: |
          go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
      - name: Generate Change Log & Release Note
        env:
          RELEASE_TAG: ${{ github.event.inputs.semver }}
        run: |
          git tag ${RELEASE_TAG}
          git-chglog ${RELEASE_TAG} > CHANGELOG.${RELEASE_TAG}.md
          if [[ -f CHANGELOG.md ]]; then
            cat CHANGELOG.md >> CHANGELOG.${RELEASE_TAG}.md
          fi
          mv CHANGELOG.${RELEASE_TAG}.md CHANGELOG.md
          cp CHANGELOG.md Assets/haechi.face.unity.sdk/
          git-chglog ${RELEASE_TAG} > RELEASE_NOTE.md
          
      - run: |
          echo "Assets/haechi.face.unity.sdk.meta" > metaList
          find Assets/haechi.face.unity.sdk/ -name \*.meta >> metaList
      - run: mkdir build
      - name: Build Unitypackage
        uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: 'build/FaceUnitySDK.unitypackage'
          include-files: metaList
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.HAECHI_GITHUB_PAT }}
        with:
          tag_name: ${{ github.event.inputs.semver }}
          release_name: ${{ github.event.inputs.semver }}
          draft: false
          prerelease: false
          body_path: ./RELEASE_NOTE.md
          files: |
            build/FaceUnitySDK.unitypackage
      - name: Commit Change Log
        run: |
          git config --local user.email "haechi@github.com"
          git config --local user.name "haechilabs"
          git add CHANGELOG.md Assets/haechi.face.unity.sdk
          git commit -m "chore: update CHANGELOG.md"
      - name: Push Change Log
        uses: ad-m/github-push-action@master
        with:
          branch: "releases/${{ github.event.inputs.semver }}"